// 타자 연습용 예시 문장 — 집필/글쓰기 서비스 성격에 맞게 짧은 문장
// 위주로 골랐다. 영어 화면일 때만 영어 문장 풀을 쓰고(일본어/중국어는
// 자체 예문 없이 한국어 문장을 그대로 쓴다), 그 외엔 한국어 문장 풀을
// 쓴다.
const KO_SENTENCES: string[] = [
  "오늘도 한 문장씩 꾸준히 써 내려갑니다.",
  "좋은 글은 한 번에 완성되지 않습니다.",
  "책상 앞에 앉아 첫 문장을 다시 고쳐 씁니다.",
  "커서가 깜빡이는 빈 화면을 마주합니다.",
  "이야기의 다음 장면이 조금씩 떠오릅니다.",
  "주인공의 마음을 더 깊이 들여다봅니다.",
  "밤늦게까지 원고를 붙잡고 씨름했습니다.",
  "마감일이 다가오니 손끝이 바빠집니다.",
  "커피 한 잔과 함께 집필을 시작합니다.",
  "오타를 고치며 문장을 다듬어 갑니다.",
  "짧은 휴식을 마치고 다시 자리에 앉습니다.",
  "머릿속 상상을 글자로 옮기는 중입니다.",
  "완결까지 남은 분량을 헤아려 봅니다.",
  "독자에게 전하고 싶은 이야기가 있습니다.",
  "낱말 하나를 고르는 데도 오래 걸립니다.",
  "새벽 공기 속에서 마지막 문단을 씁니다.",
  "어제보다 오늘 조금 더 나아졌습니다.",
  "빈 종이 위에 첫 줄을 그어 봅니다.",
  "꾸준함이 결국 좋은 글을 만듭니다.",
  "쓰고 지우기를 몇 번이고 반복합니다.",
  "쓰고 싶은 이야기가 있다면, 먼저 한 문장을 써라.",
  "완벽함은 선의 적이다.",
  "작가는 글을 쓰는 사람이 아니라, 끝까지 쓰는 사람이다.",
  "영감은 기다리는 것이 아니라 작업하는 동안 찾아오는 것이다.",
  "좋은 이야기는 좋은 질문에서 시작된다.",
  "한 문장을 고치는 일은 한 문장을 쓰는 일만큼 중요하다.",
  "오늘의 초고는 내일의 원고를 위한 재료다.",
  "쓰레기 같은 초고라도 완성된 초고는 존재한다.",
  "이야기를 머릿속에만 두면 꿈이지만, 종이에 옮기는 순간 작품이 된다.",
  "작가의 가장 강력한 도구는 특별한 재능이 아니라 매일 앉는 습관이다.",
  "천 리 길도 한 걸음부터.",
  "시작이 반이다.",
  "오늘 할 수 있는 일을 내일로 미루지 마라.",
  "성공은 준비와 기회가 만나는 지점이다.",
  "천재는 1퍼센트의 영감과 99퍼센트의 노력으로 이루어진다.",
  "나는 실패한 것이 아니다. 잘되지 않는 방법을 발견한 것이다.",
  "할 수 있다고 믿든, 할 수 없다고 믿든, 당신이 믿는 대로 될 것이다.",
  "가장 중요한 것은 포기하지 않는 것이다.",
  "위대한 일은 작은 일들이 모여 이루어진다.",
  "인내는 쓰지만 그 열매는 달다.",
  "끝날 때까지 끝난 게 아니다.",
  "오늘의 노력이 내일의 나를 만든다.",
  "넘어지는 것은 실패가 아니라, 다시 일어나지 않는 것이 실패다.",
  "어제보다 나은 오늘을 만들면 충분하다.",
  "비 온 뒤에 땅이 굳어진다.",
  "고생 끝에 낙이 온다.",
  "늦었다고 생각할 때가 가장 빠른 때일 수도 있다.",
  "작은 걸음도 멈추지 않으면 결국 목적지에 닿는다.",
  "오늘 흘린 땀은 내일의 나를 배신하지 않는다.",
  "할 수 있을까가 아니라, 어떻게 할 것인가를 생각하자.",
  "꾸준함은 재능을 이긴다.",
  "성공은 매일 반복되는 작은 노력의 합이다.",
  "당신이 할 수 있다고 믿든, 할 수 없다고 믿든, 당신의 생각이 옳다.",
  "가장 어두운 밤도 지나가고 아침은 온다.",
  "어떤 길을 선택했느냐보다, 선택한 길을 어떻게 걸어가느냐가 중요하다.",
  "목적지가 멀어 보여도 한 걸음씩 나아가면 된다.",
  "자신과의 싸움에서 이기는 사람이 결국 가장 강한 사람이다.",
  "티끌 모아 태산.",
  "공든 탑이 무너지랴.",
  "고진감래.",
  "낙숫물이 돌 뚫는다.",
  "뜻이 있는 곳에 길이 있다.",
  "한 술 밥에 배부르랴.",
  "쥐구멍에도 볕 들 날 있다.",
  "우물을 파도 한 우물을 파라.",
];

const EN_SENTENCES: string[] = [
  "Every good story starts with a single sentence.",
  "She stared at the blinking cursor for a while.",
  "The deadline is closer than it looks today.",
  "A cup of coffee makes the writing easier.",
  "He rewrote the first line one more time.",
  "The next scene is slowly taking shape.",
  "Small daily habits build a finished draft.",
  "Editing is where the real writing happens.",
  "The blank page waits for the first word.",
  "Every writer fixes typos late at night.",
  "A short break helps clear a tired mind.",
  "The character finally says what she means.",
  "Progress today is better than none at all.",
  "Readers remember stories, not perfect grammar.",
  "One word at a time, the chapter grows.",
  "The quiet morning is perfect for writing.",
  "Yesterday's draft reads better than expected.",
  "Choosing the right word can take forever.",
  "Consistency matters more than raw talent.",
  "The last paragraph ties the story together.",
];

export function pickRandomSentence(locale: string, exclude?: string): string {
  const pool = locale === "en" ? EN_SENTENCES : KO_SENTENCES;
  const filtered = exclude ? pool.filter((s) => s !== exclude) : pool;
  return filtered[Math.floor(Math.random() * filtered.length)];
}
